version: "3.9"
services:
  db:
    image: postgres:15.0
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./logs:/var/log
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  web:
    build: ./stocks_products
    command: gunicorn stocks_products.wsgi:application -b 0.0.0.0:9000
    ports:
      - "9000:9000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  nginx:
    build: nginx
    ports:
      - "1337:80"
    depends_on:
      - web
volumes:
  postgres_data: