FROM python:3.10.6

LABEL maintainer="matol 888888@888.ru"
 
ENV TZ=Europe/Moscow

WORKDIR /usr/src/stocks_products

ENV PYTHONDONTWRITEBYTECODE 1

ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .